/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const CreateTokenRequest: core.schemas.ObjectSchema<
  CreateTokenRequest.Raw,
  FernNurseryApi.token.CreateTokenRequest
> = core.schemas.object({
  ownerId: core.schemas.lazy(() => schemas.owner.OwnerId),
  description: core.schemas.string().optional(),
});

export declare namespace CreateTokenRequest {
  interface Raw {
    ownerId: schemas.owner.OwnerId.Raw;
    description?: string | null;
  }
}
