/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const TokenMetadata: core.schemas.ObjectSchema<TokenMetadata.Raw, FernNurseryApi.token.TokenMetadata> =
  core.schemas.object({
    tokenId: core.schemas.lazy(() => schemas.token.TokenId),
    ownerId: core.schemas.lazy(() => schemas.owner.OwnerId),
    description: core.schemas.string().optional(),
    createdTime: core.schemas.date(),
    status: core.schemas.lazy(() => schemas.token.TokenStatus),
  });

export declare namespace TokenMetadata {
  interface Raw {
    tokenId: schemas.token.TokenId.Raw;
    ownerId: schemas.owner.OwnerId.Raw;
    description?: string | null;
    createdTime: string;
    status: schemas.token.TokenStatus.Raw;
  }
}
