/**
 * This file auto-generated by Fern from our API Definition.
 */

import { NurseryApi } from "../../..";
import urlJoin from "url-join";
import * as schemas from "../../../schemas";
import * as core from "../../../core";

export interface Client {
  create(
    request: NurseryApi.owner.CreateOwnerRequest
  ): Promise<NurseryApi.owner.create.Response>;
  get(
    request: NurseryApi.owner.get.Request
  ): Promise<NurseryApi.owner.get.Response>;
  update(
    request: NurseryApi.owner.update.Request
  ): Promise<NurseryApi.owner.update.Response>;
}

export declare namespace Client {
  interface Options {
    _origin: string;
  }
}

export class Client implements Client {
  constructor(private readonly options: Client.Options) {}

  public async create(
    request: NurseryApi.owner.CreateOwnerRequest
  ): Promise<NurseryApi.owner.create.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/owner/"),
      method: "POST",
      body: schemas.owner.CreateOwnerRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    if (response.error.reason === "status-code") {
      switch (
        (response.error.body as schemas.owner.create.Error.Raw)?.errorName
      ) {
        case "OwnerAlreadyExistsError":
          return {
            ok: false,
            error: schemas.owner.create.Error.parse(
              response.error.body as schemas.owner.create.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async get(
    request: NurseryApi.owner.get.Request
  ): Promise<NurseryApi.owner.get.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, `/owner/${request.ownerId}`),
      method: "GET",
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.owner.Owner.parse(
          response.body as schemas.owner.Owner.Raw
        ),
      };
    }

    if (response.error.reason === "status-code") {
      switch ((response.error.body as schemas.owner.get.Error.Raw)?.errorName) {
        case "OwnerNotFoundError":
          return {
            ok: false,
            error: schemas.owner.get.Error.parse(
              response.error.body as schemas.owner.get.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async update(
    request: NurseryApi.owner.update.Request
  ): Promise<NurseryApi.owner.update.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, `/owner/${request.ownerId}`),
      method: "PUT",
      body: request._body,
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.owner.Owner.parse(
          response.body as schemas.owner.Owner.Raw
        ),
      };
    }

    if (response.error.reason === "status-code") {
      switch (
        (response.error.body as schemas.owner.update.Error.Raw)?.errorName
      ) {
        case "OwnerNotFoundError":
          return {
            ok: false,
            error: schemas.owner.update.Error.parse(
              response.error.body as schemas.owner.update.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
