/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";
import * as core from "../../../core";

export declare namespace Client {
  interface Options {
    environment: string;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async create(request: FernNursery.CreateOwnerRequest): Promise<FernNursery.owner.create.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment, "/owner"),
      method: "POST",
      body: await serializers.owner.create.Request.json({
        ownerId: request.ownerId,
        data: request.data,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: undefined,
      };
    }

    if (_response.error.reason === "status-code") {
      switch ((_response.error.body as serializers.owner.create.Error.Raw)?.errorName) {
        case "OwnerAlreadyExistsError":
          return {
            ok: false,
            error: await serializers.owner.create.Error.parse(
              _response.error.body as serializers.owner.create.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: FernNursery.owner.create.Error._unknown(_response.error),
    };
  }

  public async get(ownerId: FernNursery.OwnerId): Promise<FernNursery.owner.get.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment, `/owner/${ownerId}`),
      method: "GET",
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.owner.get.Response.parse(_response.body as serializers.owner.get.Response.Raw),
      };
    }

    if (_response.error.reason === "status-code") {
      switch ((_response.error.body as serializers.owner.get.Error.Raw)?.errorName) {
        case "OwnerNotFoundError":
          return {
            ok: false,
            error: await serializers.owner.get.Error.parse(_response.error.body as serializers.owner.get.Error.Raw),
          };
      }
    }

    return {
      ok: false,
      error: FernNursery.owner.get.Error._unknown(_response.error),
    };
  }

  public async update(
    ownerId: FernNursery.OwnerId,
    request: FernNursery.UpdateOwnerRequest
  ): Promise<FernNursery.owner.update.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment, `/owner/${ownerId}`),
      method: "PUT",
      body: await serializers.owner.update.Request.json({
        data: request.data,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.owner.update.Response.parse(_response.body as serializers.owner.update.Response.Raw),
      };
    }

    if (_response.error.reason === "status-code") {
      switch ((_response.error.body as serializers.owner.update.Error.Raw)?.errorName) {
        case "OwnerNotFoundError":
          return {
            ok: false,
            error: await serializers.owner.update.Error.parse(
              _response.error.body as serializers.owner.update.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: FernNursery.owner.update.Error._unknown(_response.error),
    };
  }
}
