/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";
import * as core from "../../../core";

export type Response = core.APIResponse<void, FernNurseryApi.owner.create.Error>;
export type Error =
  | FernNurseryApi.owner.create.Error.OwnerAlreadyExistsError
  | FernNurseryApi.owner.create.Error._Unknown;

export declare namespace Error {
  interface OwnerAlreadyExistsError extends _Utils {
    errorName: "OwnerAlreadyExistsError";
  }

  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: FernNurseryApi.owner.create.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    ownerAlreadyExistsError: () => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  ownerAlreadyExistsError: (): FernNurseryApi.owner.create.Error.OwnerAlreadyExistsError => {
    const valueWithoutVisit: Omit<FernNurseryApi.owner.create.Error.OwnerAlreadyExistsError, "_visit"> = {
      errorName: "OwnerAlreadyExistsError",
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: FernNurseryApi.owner.create.Error.OwnerAlreadyExistsError, visitor: FernNurseryApi.owner.create.Error._Visitor<_Result>) {
      return FernNurseryApi.owner.create.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: FernNurseryApi.owner.create.Error,
    visitor: FernNurseryApi.owner.create.Error._Visitor<_Result>
  ): _Result => {
    switch (value.errorName) {
      case "OwnerAlreadyExistsError":
        return visitor.ownerAlreadyExistsError();
      default:
        return visitor._other(visitor as any);
    }
  },
} as const;
