/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";

export interface CreateTokenResponse {
  token: string;
  tokenId: FernNurseryApi.token.TokenId;
}
