/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";

export interface CreateTokenRequest {
  ownerId: FernNurseryApi.owner.OwnerId;
  description?: string;
}
