/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const CustomOwnerData: core.schemas.Schema<serializers.CustomOwnerData.Raw, FernNursery.CustomOwnerData> =
  core.schemas.unknown();

export declare namespace CustomOwnerData {
  type Raw = unknown;
}
