/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const Owner: core.schemas.ObjectSchema<serializers.Owner.Raw, FernNursery.Owner> = core.schemas.object({
  ownerId: core.schemas.lazy(async () => (await import("../..")).OwnerId),
  data: core.schemas.lazy(async () => (await import("../..")).CustomOwnerData),
});

export declare namespace Owner {
  interface Raw {
    ownerId: serializers.OwnerId.Raw;
    data?: serializers.CustomOwnerData.Raw;
  }
}
