/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";
import * as core from "../../../core";
import * as serializers from "../..";

export const Owner: core.schemas.ObjectSchema<Owner.Raw, FernNurseryApi.Owner> = core.schemas.object({
  ownerId: core.schemas.lazy(async () => (await import("../..")).OwnerId),
  data: core.schemas.unknown(),
});

export declare namespace Owner {
  interface Raw {
    ownerId: serializers.OwnerId.Raw;
    data?: unknown;
  }
}
