/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const UpdateOwnerRequest: core.schemas.ObjectSchema<UpdateOwnerRequest.Raw, FernNursery.UpdateOwnerRequest> =
  core.schemas.object({
    data: core.schemas.unknown(),
  });

export declare namespace UpdateOwnerRequest {
  interface Raw {
    data?: unknown;
  }
}
