/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AcmeGizmoApi } from "@cognodyne/nursery";

export interface Movie {
  id: AcmeGizmoApi.MovieId;
  title: string;
  /** The rating scale is one to five stars */
  rating: number;
}
