/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";
import urlJoin from "url-join";
import * as schemas from "../../../schemas";
import * as core from "../../../core";

export interface Client {
  create(request: FernNurseryApi.token.CreateTokenRequest): Promise<FernNurseryApi.token.create.Response>;
  getTokenMetadata(
    request: FernNurseryApi.token.GetTokenMetadataRequest
  ): Promise<FernNurseryApi.token.getTokenMetadata.Response>;
  getTokensForOwner(
    request: FernNurseryApi.token.getTokensForOwner.Request
  ): Promise<FernNurseryApi.token.getTokensForOwner.Response>;
}

export declare namespace Client {
  interface Options {
    _origin: string;
  }
}

export class Client implements Client {
  constructor(private readonly options: Client.Options) {}

  public async create(request: FernNurseryApi.token.CreateTokenRequest): Promise<FernNurseryApi.token.create.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/tokens/create"),
      method: "POST",
      body: schemas.token.CreateTokenRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.token.CreateTokenResponse.parse(response.body as schemas.token.CreateTokenResponse.Raw),
      };
    }

    if (response.error.reason === "status-code") {
      switch ((response.error.body as schemas.token.create.Error.Raw)?.errorName) {
        case "OwnerNotFoundError":
          return {
            ok: false,
            error: schemas.token.create.Error.parse(response.error.body as schemas.token.create.Error.Raw),
          };
      }
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async getTokenMetadata(
    request: FernNurseryApi.token.GetTokenMetadataRequest
  ): Promise<FernNurseryApi.token.getTokenMetadata.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, "/tokens/metadata"),
      method: "POST",
      body: schemas.token.GetTokenMetadataRequest.json(request),
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.token.TokenMetadata.parse(response.body as schemas.token.TokenMetadata.Raw),
      };
    }

    if (response.error.reason === "status-code") {
      switch ((response.error.body as schemas.token.getTokenMetadata.Error.Raw)?.errorName) {
        case "TokenNotFoundError":
          return {
            ok: false,
            error: schemas.token.getTokenMetadata.Error.parse(
              response.error.body as schemas.token.getTokenMetadata.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }

  public async getTokensForOwner(
    request: FernNurseryApi.token.getTokensForOwner.Request
  ): Promise<FernNurseryApi.token.getTokensForOwner.Response> {
    const response = await core.fetcher({
      url: urlJoin(this.options._origin, `/tokens/owner/${request.ownerId}`),
      method: "GET",
    });
    if (response.ok) {
      return {
        ok: true,
        body: schemas.token.getTokensForOwner.Response.parse(response.body as schemas.token.TokenMetadata.Raw[]),
      };
    }

    if (response.error.reason === "status-code") {
      switch ((response.error.body as schemas.token.getTokensForOwner.Error.Raw)?.errorName) {
        case "OwnerNotFoundError":
          return {
            ok: false,
            error: schemas.token.getTokensForOwner.Error.parse(
              response.error.body as schemas.token.getTokensForOwner.Error.Raw
            ),
          };
      }
    }

    return {
      ok: false,
      error: {
        errorName: undefined,
        content: response.error,
        _visit: (visitor) => visitor._other(response.error),
      },
    };
  }
}
