/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export type Response = core.APIResponse<FernNursery.TokenMetadata, FernNursery.token.getTokenMetadata.Error>;
export type Error =
  | FernNursery.token.getTokenMetadata.Error.TokenNotFoundError
  | FernNursery.token.getTokenMetadata.Error._Unknown;

export declare namespace Error {
  interface TokenNotFoundError extends _Utils {
    errorName: "TokenNotFoundError";
  }

  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: FernNursery.token.getTokenMetadata.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    tokenNotFoundError: () => _Result;
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  tokenNotFoundError: (): FernNursery.token.getTokenMetadata.Error.TokenNotFoundError => {
    const valueWithoutVisit: Omit<FernNursery.token.getTokenMetadata.Error.TokenNotFoundError, "_visit"> = {
      errorName: "TokenNotFoundError",
    };
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: FernNursery.token.getTokenMetadata.Error.TokenNotFoundError, visitor: FernNursery.token.getTokenMetadata.Error._Visitor<_Result>) {
      return FernNursery.token.getTokenMetadata.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: FernNursery.token.getTokenMetadata.Error,
    visitor: FernNursery.token.getTokenMetadata.Error._Visitor<_Result>
  ): _Result => {
    switch (value.errorName) {
      case "TokenNotFoundError":
        return visitor.tokenNotFoundError();
      default:
        return visitor._other(visitor as any);
    }
  },
} as const;
