/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const CreateTokenResponse: core.schemas.ObjectSchema<
  CreateTokenResponse.Raw,
  FernNurseryApi.token.CreateTokenResponse
> = core.schemas.object({
  token: core.schemas.string(),
  tokenId: core.schemas.lazy(() => serializers.token.TokenId),
});

export declare namespace CreateTokenResponse {
  interface Raw {
    token: string;
    tokenId: serializers.token.TokenId.Raw;
  }
}
