/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";
import * as serializers from "../..";

export const CreateTokenRequest: core.schemas.ObjectSchema<CreateTokenRequest.Raw, FernNursery.CreateTokenRequest> =
  core.schemas.object({
    ownerId: core.schemas.lazy(async () => (await import("../..")).OwnerId),
    description: core.schemas.string().optional(),
  });

export declare namespace CreateTokenRequest {
  interface Raw {
    ownerId: serializers.OwnerId.Raw;
    description?: string | null;
  }
}
