/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const CreateTokenResponse: core.schemas.ObjectSchema<
  serializers.CreateTokenResponse.Raw,
  FernNursery.CreateTokenResponse
> = core.schemas.object({
  token: core.schemas.string(),
  tokenId: core.schemas.lazy(async () => (await import("../..")).TokenId),
});

export declare namespace CreateTokenResponse {
  interface Raw {
    token: string;
    tokenId: serializers.TokenId.Raw;
  }
}
