/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";
import * as core from "../../../core";

export const GetTokenMetadataRequest: core.schemas.ObjectSchema<
  GetTokenMetadataRequest.Raw,
  FernNurseryApi.GetTokenMetadataRequest
> = core.schemas.object({
  token: core.schemas.string(),
});

export declare namespace GetTokenMetadataRequest {
  interface Raw {
    token: string;
  }
}
