/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";
import * as core from "../../../core";

export const RevokeTokenRequest: core.schemas.ObjectSchema<RevokeTokenRequest.Raw, FernNurseryApi.RevokeTokenRequest> =
  core.schemas.object({
    token: core.schemas.string(),
  });

export declare namespace RevokeTokenRequest {
  interface Raw {
    token: string;
  }
}
