/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";
import * as serializers from "../..";

export const TokenMetadata: core.schemas.ObjectSchema<TokenMetadata.Raw, FernNursery.TokenMetadata> =
  core.schemas.object({
    tokenId: core.schemas.lazy(async () => (await import("../..")).TokenId),
    ownerId: core.schemas.lazy(async () => (await import("../..")).OwnerId),
    description: core.schemas.string().optional(),
    createdTime: core.schemas.date(),
    status: core.schemas.lazy(async () => (await import("../..")).TokenStatus),
  });

export declare namespace TokenMetadata {
  interface Raw {
    tokenId: serializers.TokenId.Raw;
    ownerId: serializers.OwnerId.Raw;
    description?: string | null;
    createdTime: string;
    status: serializers.TokenStatus.Raw;
  }
}
