/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";
import * as core from "../../../core";

export const TokenId: core.schemas.Schema<TokenId.Raw, FernNurseryApi.TokenId> = core.schemas.string();

export declare namespace TokenId {
  type Raw = string;
}
