/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

/**
 * @example
 *     {
 *         ownerId: "some-owner-id",
 *         data: {
 *             "custom-key": "custom-value"
 *         }
 *     }
 */
export interface Owner {
  ownerId: FernNursery.OwnerId;
  data?: FernNursery.CustomOwnerData;
}
