/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

/**
 * Unique id for an owner.
 */
export type OwnerId = string;

export function OwnerId(value: string): FernNursery.OwnerId {
  return value as unknown as FernNursery.OwnerId;
}
