/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";

/**
 * Unique id for an owner.
 */
export type OwnerId = string;

export function OwnerId(value: string): FernNurseryApi.OwnerId {
  return value as unknown as FernNurseryApi.OwnerId;
}
