/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { AcmeGizmoApi } from "@cognodyne/nursery";
import * as core from "../../../core";

export type Response = core.APIResponse<AcmeGizmoApi.MovieId, AcmeGizmoApi.imdb.createMovie.Error>;
export type Error = AcmeGizmoApi.imdb.createMovie.Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    statusCode: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <_Result>(visitor: AcmeGizmoApi.imdb.createMovie.Error._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    _other: (value: core.Fetcher.Error) => _Result;
  }
}

export const Error = {
  _unknown: (fetcherError: core.Fetcher.Error): AcmeGizmoApi.imdb.createMovie.Error._Unknown => {
    const valueWithoutVisit = fetcherError as unknown as Omit<AcmeGizmoApi.imdb.createMovie.Error._Unknown, "_visit">;
    return core.addNonEnumerableProperty(valueWithoutVisit, "_visit", function <
      _Result
    >(this: AcmeGizmoApi.imdb.createMovie.Error._Unknown, visitor: AcmeGizmoApi.imdb.createMovie.Error._Visitor<_Result>) {
      return AcmeGizmoApi.imdb.createMovie.Error._visit(this, visitor);
    });
  },

  _visit: <_Result>(
    value: AcmeGizmoApi.imdb.createMovie.Error,
    visitor: AcmeGizmoApi.imdb.createMovie.Error._Visitor<_Result>
  ): _Result => {
    switch (value.statusCode) {
      default:
        return visitor._other(value as any);
    }
  },
} as const;
