/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as schemas from "../..";
import { NurseryApi } from "../../..";
import * as core from "../../../core";

export const Response: core.schemas.Schema<
  schemas.token.TokenMetadata.Raw[],
  NurseryApi.token.TokenMetadata[]
> = core.schemas.list(
  core.schemas.lazyObject(() => schemas.token.TokenMetadata)
);
export const Error: core.schemas.Schema<
  Error.Raw,
  NurseryApi.token.getTokensForOwner.Error
> = core.schemas
  .union("errorName", {
    OwnerNotFoundError: core.schemas.object({}),
  })
  .transform<NurseryApi.token.getTokensForOwner.Error>({
    parse: (value) => {
      switch (value.errorName) {
        case "OwnerNotFoundError": {
          return {
            ...value,
            _visit: (visitor) => visitor.ownerNotFoundError(),
          };
        }
      }
    },
    json: (value) => value as any,
  });

export declare namespace Error {
  type Raw = Error.OwnerNotFoundError;

  interface OwnerNotFoundError {
    errorName: "OwnerNotFoundError";
  }
}
