/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { AcmeGizmoApi } from "@cognodyne/nursery";
import * as core from "../../../core";

export const MovieDoesNotExistError: core.schemas.Schema<
  serializers.MovieDoesNotExistError.Raw,
  AcmeGizmoApi.MovieDoesNotExistError
> = core.schemas.lazy(async () => (await import("../..")).MovieId);

export declare namespace MovieDoesNotExistError {
  type Raw = serializers.MovieId.Raw;
}
