/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const CreateOwnerRequest: core.schemas.ObjectSchema<
  CreateOwnerRequest.Raw,
  FernNurseryApi.owner.CreateOwnerRequest
> = core.schemas.object({
  ownerId: core.schemas.lazy(() => schemas.owner.OwnerId),
  data: core.schemas.unknown(),
});

export declare namespace CreateOwnerRequest {
  interface Raw {
    ownerId: schemas.owner.OwnerId.Raw;
    data?: unknown;
  }
}
