/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";
import * as core from "../../../core";

export const UpdateOwnerRequest: core.schemas.ObjectSchema<
  UpdateOwnerRequest.Raw,
  FernNurseryApi.owner.UpdateOwnerRequest
> = core.schemas.object({
  data: core.schemas.unknown(),
});

export declare namespace UpdateOwnerRequest {
  interface Raw {
    data?: unknown;
  }
}
