/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { AcmeGizmoApi } from "@cognodyne/nursery";
import * as core from "../../../core";

export const Movie: core.schemas.ObjectSchema<serializers.Movie.Raw, AcmeGizmoApi.Movie> = core.schemas.object({
  id: core.schemas.lazy(async () => (await import("../..")).MovieId),
  title: core.schemas.string(),
  rating: core.schemas.number(),
});

export declare namespace Movie {
  interface Raw {
    id: serializers.MovieId.Raw;
    title: string;
    rating: number;
  }
}
