/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { AcmeGizmoApi } from "@cognodyne/nursery";
import * as core from "../../../core";

export const MovieId: core.schemas.Schema<serializers.MovieId.Raw, AcmeGizmoApi.MovieId> = core.schemas.string();

export declare namespace MovieId {
  type Raw = string;
}
