/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.owner.create.Request.Raw, FernNursery.CreateOwnerRequest> =
  core.schemas.object({
    ownerId: core.schemas.lazy(async () => (await import("../..")).OwnerId),
    data: core.schemas.unknown(),
  });

export declare namespace Request {
  interface Raw {
    ownerId: serializers.OwnerId.Raw;
    data?: unknown;
  }
}

export const Error: core.schemas.Schema<serializers.owner.create.Error.Raw, FernNursery.owner.create.Error> =
  core.schemas
    .union("errorName", {
      OwnerAlreadyExistsError: core.schemas.object({}),
    })
    .transform<FernNursery.owner.create.Error>({
      parse: (value) => {
        switch (value.errorName) {
          case "OwnerAlreadyExistsError":
            return FernNursery.owner.create.Error.ownerAlreadyExistsError();
        }
      },
      json: (value) => value as any,
    });

export declare namespace Error {
  type Raw = Error.OwnerAlreadyExistsError;

  interface OwnerAlreadyExistsError {
    errorName: "OwnerAlreadyExistsError";
  }
}
