/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.owner.get.Response.Raw, FernNursery.Owner> =
  core.schemas.lazyObject(async () => (await import("../..")).Owner);

export declare namespace Response {
  type Raw = serializers.Owner.Raw;
}

export const Error: core.schemas.Schema<serializers.owner.get.Error.Raw, FernNursery.owner.get.Error> = core.schemas
  .union("errorName", {
    OwnerNotFoundError: core.schemas.object({}),
  })
  .transform<FernNursery.owner.get.Error>({
    parse: (value) => {
      switch (value.errorName) {
        case "OwnerNotFoundError":
          return FernNursery.owner.get.Error.ownerNotFoundError();
      }
    },
    json: (value) => value as any,
  });

export declare namespace Error {
  type Raw = Error.OwnerNotFoundError;

  interface OwnerNotFoundError {
    errorName: "OwnerNotFoundError";
  }
}
