/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.owner.update.Request.Raw, FernNursery.UpdateOwnerRequest> =
  core.schemas.object({
    data: core.schemas.lazy(async () => (await import("../..")).CustomOwnerData),
  });

export declare namespace Request {
  interface Raw {
    data?: serializers.CustomOwnerData.Raw;
  }
}

export const Response: core.schemas.Schema<serializers.owner.update.Response.Raw, FernNursery.Owner> =
  core.schemas.lazyObject(async () => (await import("../..")).Owner);

export declare namespace Response {
  type Raw = serializers.Owner.Raw;
}

export const Error: core.schemas.Schema<serializers.owner.update.Error.Raw, FernNursery.owner.update.Error> =
  core.schemas
    .union("errorName", {
      OwnerNotFoundError: core.schemas.object({}),
    })
    .transform<FernNursery.owner.update.Error>({
      parse: (value) => {
        switch (value.errorName) {
          case "OwnerNotFoundError":
            return FernNursery.owner.update.Error.ownerNotFoundError();
        }
      },
      json: (value) => value as any,
    });

export declare namespace Error {
  type Raw = Error.OwnerNotFoundError;

  interface OwnerNotFoundError {
    errorName: "OwnerNotFoundError";
  }
}
