/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";
import * as core from "../../../core";

export const Error: core.schemas.Schema<Error.Raw, FernNursery.owner.update.Error> = core.schemas
  .union("errorName", {
    OwnerNotFoundError: core.schemas.object({}),
  })
  .transform<FernNursery.owner.update.Error>({
    parse: (value) => {
      switch (value.errorName) {
        case "OwnerNotFoundError":
          return FernNursery.owner.update.Error.ownerNotFoundError();
      }
    },
    json: (value) => value as any,
  });

export declare namespace Error {
  type Raw = Error.OwnerNotFoundError;

  interface OwnerNotFoundError {
    errorName: "OwnerNotFoundError";
  }
}
