/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { AcmeGizmoApi } from "@cognodyne/nursery";
import * as core from "../../../core";

export const Request: core.schemas.Schema<serializers.imdb.createMovie.Request.Raw, AcmeGizmoApi.CreateMovieRequest> =
  core.schemas.lazyObject(async () => (await import("../..")).CreateMovieRequest);

export declare namespace Request {
  type Raw = serializers.CreateMovieRequest.Raw;
}

export const Response: core.schemas.Schema<serializers.imdb.createMovie.Response.Raw, AcmeGizmoApi.MovieId> =
  core.schemas.lazy(async () => (await import("../..")).MovieId);

export declare namespace Response {
  type Raw = serializers.MovieId.Raw;
}
