/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { AcmeGizmoApi } from "@cognodyne/nursery";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.imdb.getMovie.Response.Raw, AcmeGizmoApi.Movie> =
  core.schemas.lazyObject(async () => (await import("../..")).Movie);

export declare namespace Response {
  type Raw = serializers.Movie.Raw;
}
