/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "../../..";

export interface CreateOwnerRequest {
  ownerId: FernNurseryApi.owner.OwnerId;
  /** Store arbitrary data about the owner. */
  data?: unknown;
}
