/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

export interface CreateTokenResponse {
  token: string;
  tokenId: FernNursery.TokenId;
}
