/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

export interface CreateTokenRequest {
  ownerId: FernNursery.OwnerId;
  description?: string;
}
