/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

/**
 * @example
 *     {
 *         token: "some-token-value",
 *         tokenId: "some-token-id"
 *     }
 */
export interface CreateTokenResponse {
  token: string;
  tokenId: FernNursery.TokenId;
}
