/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";

export interface CreateTokenRequest {
  ownerId: FernNurseryApi.OwnerId;
  description?: string;
}
