/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNurseryApi } from "@fern-api/nursery";

export type TokenId = string;

export function TokenId(value: string): FernNurseryApi.TokenId {
  return value as unknown as FernNurseryApi.TokenId;
}
