/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

export interface TokenMetadata {
  tokenId: FernNursery.TokenId;
  ownerId: FernNursery.OwnerId;
  description?: string;
  createdTime: Date;
  status: FernNursery.TokenStatus;
}
