/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FernNursery } from "@fern-api/nursery";

export type TokenId = string;

export function TokenId(value: string): FernNursery.TokenId {
  return value as unknown as FernNursery.TokenId;
}
