/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Client as ImdbClient } from "./resources/imdb/client/Client";

export declare namespace AcmeGizmoApiClient {
  interface Options {
    environment: string;
  }
}

export class AcmeGizmoApiClient {
  constructor(private readonly options: AcmeGizmoApiClient.Options) {}

  #imdb: ImdbClient | undefined;

  public get imdb(): ImdbClient {
    return (this.#imdb ??= new ImdbClient(this.options));
  }
}
