/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Prod: "nursery.buildwithfern.com",
  Dev: "nursery-dev.buildwithfern.com",
} as const;

export type Environment = typeof Environment.Prod | typeof Environment.Dev;
