/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import { Client as OwnerClient } from "./resources/owner/client/Client";
import { Client as TokenClient } from "./resources/token/client/Client";

export declare namespace FernNurseryApiClient {
  interface Options {
    environment?: environments.Environment | string;
  }
}

export class FernNurseryApiClient {
  constructor(private readonly options: FernNurseryApiClient.Options) {}

  #owner: OwnerClient | undefined;

  public get owner(): OwnerClient {
    return (this.#owner ??= new OwnerClient(this.options));
  }

  #token: TokenClient | undefined;

  public get token(): TokenClient {
    return (this.#token ??= new TokenClient(this.options));
  }
}
