/**
 * This file auto-generated by Fern from our API Definition.
 */

import { Client as OwnerServiceClient } from "./owner/client/Client";
import { Client as TokenServiceClient } from "./token/client/Client";

export namespace Client {
  export interface Options {
    _origin: string;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #owner: OwnerServiceClient | undefined;

  public get owner(): OwnerServiceClient {
    return (this.#owner ??= new OwnerServiceClient({
      _origin: this.options._origin,
    }));
  }

  #token: TokenServiceClient | undefined;

  public get token(): TokenServiceClient {
    return (this.#token ??= new TokenServiceClient({
      _origin: this.options._origin,
    }));
  }
}
